#pragma once

#include "board_common.h"
#include "sdkconfig.h"

#define BOARD_NAME "Waveshare ESP32-S3-Touch-LCD-1.54"
#define BOARD_DESCRIPTION \
  "Waveshare ESP32-S3-Touch-LCD-1.54 with ST7789 display and CST816S touch"

// SPI display pins
#define BOARD_SPI_SCLK_GPIO CONFIG_SPI_SCLK_IO
#define BOARD_SPI_MOSI_GPIO CONFIG_SPI_MOSI_IO
#define BOARD_SPI_MISO_GPIO CONFIG_SPI_MISO_IO
#define BOARD_SPI_CS_GPIO   CONFIG_SPI_CS_IO
#define BOARD_SPI_DC_GPIO   CONFIG_SPI_DC_IO
#define BOARD_SPI_RST_GPIO  CONFIG_SPI_RST_IO
#define BOARD_SPI_BL_GPIO   CONFIG_SPI_BL_IO

// I2C touch controller (CST816S)
#define BOARD_I2C_TOUCH_SDA_GPIO CONFIG_I2C_TOUCH_SDA_IO
#define BOARD_I2C_TOUCH_SCL_GPIO CONFIG_I2C_TOUCH_SCL_IO
#define BOARD_I2C_TOUCH_RST_GPIO CONFIG_I2C_TOUCH_RST_IO
#define BOARD_I2C_TOUCH_INT_GPIO CONFIG_I2C_TOUCH_INT_IO

// LED backlight (PWM)
#define BOARD_LED_BL_PWM_TIMER   CONFIG_LED_BL_PWM_TIMER
#define BOARD_LED_BL_PWM_CHANNEL CONFIG_LED_BL_PWM_CHANNEL

// LED configuration
#define BOARD_LED_STATUS_GPIO CONFIG_LED_STATUS_GPIO
#define BOARD_LED_ERROR_GPIO  CONFIG_LED_ERROR_GPIO
#define BOARD_LED_RGB_GPIO    CONFIG_LED_RGB_GPIO

// I2S configuration (external DAC)
#define BOARD_I2S_BCK_GPIO CONFIG_I2S_BCK_IO
#define BOARD_I2S_WS_GPIO  CONFIG_I2S_WS_IO
#define BOARD_I2S_DO_GPIO  CONFIG_I2S_DO_IO
#define BOARD_I2S_GND_GPIO CONFIG_I2S_GND_IO
#define BOARD_I2S_VCC_GPIO CONFIG_I2S_VCC_IO

// Control GPIOs
#define BOARD_JACK_GPIO       CONFIG_JACK_GPIO
#define BOARD_SPKFAULT_GPIO   CONFIG_SPKFAULT_GPIO
#define BOARD_MUTE_GPIO       CONFIG_MUTE_GPIO
#define BOARD_MUTE_GPIO_LEVEL CONFIG_MUTE_GPIO_LEVEL

// DAC I2C (optional)
#define BOARD_I2C_SDA_GPIO CONFIG_DAC_I2C_SDA
#define BOARD_I2C_SCL_GPIO CONFIG_DAC_I2C_SCL

// Battery monitoring
